spring:
  application:
    name: @project.artifactId@

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://conversion-eureka:1234/eureka/

zuul:
  routes:
    serviceId:
      serviceId: your_server_id
      path: /**
    serviceId2:
      serviceId: your_server2_id
      path: /**

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 300000
